### ISSUE TITLE
Add Laravel Dusk support

### ISSUE THREAD

**Issue by DCzajkowski** [zaynali53/DotENV#2]
Hello,
In the newest version of Laravel, there was an introduction of [Laravel Dusk](https://laravel.com/docs/5.4/dusk). It uses a special `.env.dusk.{environment}` file e.g. `.env.dusk.local` etc.

Could you please add support to all `.env*` files, or if impossible, support of `.env.dusk.local` etc.?

Thanks in advance :)

**Comment by zaynali53** [comment]
@DCzajkowski Thanks for the feedback. :-)

Yes. I've added support for `.env.dusk.local`. 

Unfortunately, in sublime text there is no way to achieve something like `.env*`. This is because supported file types are stored as an array not `Regular expression`. So, i've to manually add new file type each time.

**Comment by DCzajkowski** [comment]
Awesome! Will that add an icon in the sidebar?

**Comment by zaynali53** [comment]
Yes. These are all the supported file types with icon.

![capture](https://cloud.githubusercontent.com/assets/8646770/26163352/d4db05e8-3b42-11e7-84a8-95d7422fc52f.JPG)

Theme: [Material Theme](https://github.com/equinusocio/material-theme)
Icon Pack: [a-file-icon](https://github.com/ihodev/a-file-icon)

**Comment by DCzajkowski** [comment]
Great job! Thank you ❤️😊
